#!/usr/bin/env bash

# PDF generation
pandoc \
  --toc \
  -o "A beginner's guide to countable ordinals.pdf" \
  "A beginner's guide to countable ordinals.md"

# HTML generation
pandoc \
  --standalone \
  --include-in-header html/Alegreya.html \
  --include-in-header html/TOC.html \
  -V lang=en \
  --css css/style.css \
  --mathjax \
  --toc \
  -o "index.html" \
  "A beginner's guide to countable ordinals.md"

# HTML generation
pandoc \
  --standalone \
  --mathjax \
  --toc \
  -o "index-default.html" \
  "A beginner's guide to countable ordinals.md"