#!/usr/bin/env bash

# PDF generation
pandoc \
  --toc \
  -o "A beginner's guide to countable ordinals.pdf" 
  "A beginner's guide to countable ordinals.md"

# HTML generation
pandoc \
  --standalone \
  --include-in-header html/Alegreya.html \
  -V mainfont=Alegreya \
  -V fontsize="24px" \
  --mathjax \
  --toc \
  -o "index.html" \
  "A beginner's guide to countable ordinals.md"